apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: migrate/migrate
        command: [
          "-path", "/migrations",
          "-database", "postgres://postgres:postgres@restaurant-db-service:5432/fiap_fast_food?sslmode=disable",
          "up"
        ]
        volumeMounts:
        - name: migrations-volume
          mountPath: /migrations
      restartPolicy: Never
      volumes:
      - name: migrations-volume
        configMap:
          name: migrations-configmap
  backoffLimit: 4
